name: API 배포

# on: workflow_dispatch
on:
  push:
    branches: master

jobs:
  deply:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: API Repo에서 서비스용 API 파일을 가져옵니다.
        run: |
          curl \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_KEY }}" \
              -H "Accept: application/vnd.github+json" \
              -o result.json \
              https://api.github.com/repos/arcmonster/api-acrmonster/contents/service_api.zip
          
          
          ls -al
          cat result.json
          
      - name: Download Url 추출
        id: download
        run: |
          v=$(jq .download_url result.json)
          echo "value=$v" >> "$GITHUB_OUTPUT"
        
      - run: |
          wget  -O service_api.zip ${{ steps.download.outputs.value }}
          
      - run: ls -al
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq service_api.zip -d service_api
      - run: ls ./service_api -al
        
      - name: move api files 
        run: |
          rm -rf ./app/api/server
          
          mkdir -p ./app/api/server
          mkdir -p ./app/lib/api
          ls -al
          
          cp -rf ./service_api/api/server ./app/api/server
          cp -rf ./service_api/local_service.ts ./app/lib/api/
          cp -rf ./service_api/ArcApiServiceMiddle.ts ./app/lib/api/
          
          sudo rm -rf ./service_api
          sudo rm ./result.json ./service_api.zip
          
      - name: Api Push
        run: |
          git add .
          git config --local user.email 'gcshin@arcmonster.co.kr'
          git config --local user.name 'api 자동배포'
          git commit -m 'api 자동배포'
          git push
      
