name: API 배포

# on: workflow_dispatch
on:
  push:
    branches: master

jobs:
  deply:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: API Repo에서 서비스용 API 파일을 가져옵니다.
        run: |
          curl \
              -H "Authorization: Bearer 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" \
              -H "Accept: application/vnd.github+json" \
              -o result.json \
              https://api.github.com/repos/arcmonster/api-acrmonster/contents/service_api.zip
          
          ls -al
          cat result.json
          
      - name: load result to json
        id: api_file
        run: jq .api_file result.js -r
          
      - name: Show JSON
        run: echo "api_file ${{ steps.api_file..outputs }}"
