name: API 배포

# on: workflow_dispatch
on:
  push:
    branches: master

jobs:
  deply:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: API Repo에서 서비스용 API 파일을 가져옵니다.
        run: |
          curl \
              -H "Authorization: Bearer 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" \
              -H "Accept: application/vnd.github+json" \
              -o result.json \
              https://api.github.com/repos/arcmonster/api-acrmonster/contents/service_api.zip
          
          ls -al
          cat result.json
          
      - name: load result to json
        run: jq .name result.json
