name: API 배포

# on: workflow_dispatch
on:
  push:
    branches: master

jobs:
  deply:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: API Repo에서 서비스용 API 파일을 가져옵니다.
        run: |
          curl \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_KEY }}" \
              -H "Accept: application/vnd.github+json" \
              -o result.json \
              https://api.github.com/repos/arcmonster/api-acrmonster/contents/service_api.zip
          
          
          ls -al
          cat result.json
#       - run: |
#           wget ${{ jq .download_url result.json }}
      - name: load result to json
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "service_api.zip"
          fileDir: "./"
          encodedString: jq .content result.json
          
      - run: ls -al
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq service_api.zip -d service_api
      - run: ls ./service_api -al
